CHANGELOG.md, src/components/sections/ProductDetails/ProductDetails.tsx, src/components/sections/ProductDetails/product-details.scss, src/components/ui/ImageGallery/ImageGallery.tsx, src/components/ui/ImageGallery/ImageGallerySelector.tsx, src/components/ui/ImageGallery/image-gallery-selector.scss, src/components/ui/ImageGallery/image-gallery.scss, src/styles/pages/pdp.scss, store.config.js
Ported from base.store, for a full description relate to the original PR: https://github.com/vtex-sites/base.store/pull/409
=> Styles and Integrates ImageGallery at PDP

CHANGELOG.md
It adds links to the PRs, especially because some of them were from https://github.com/vtex-sites/base.store and not the current repo.
It also fixes this markdown:
=> chore: Better organize the Changelog

vtex.env
enable node_modules cache for faster builds
=> chore: Enable node_modules cache

lighthouserc.js, package.json, vtex.env, yarn.lock
Uses new WebOps framework cache env vars for speeding up builds.
=> chore: Framework cache

CHANGELOG.md, src/components/ui/ImageGallery/ImageGallerySelector.tsx
This enhances some bits of code to enhance readability/reduce number of function calls as per @eduardoformiga comments on https://github.com/vtex-sites/gatsby.store/pull/27
Nothing should have changed.
@eduardoformiga
=> chore: FSSS-280 Code Improvements

.storybook/storybook.css, src/components/product/OutOfStock/OutOfStock.stories.mdx, src/components/sections/BannerText/BannerText.stories.mdx, src/components/sections/Incentives/Incentives.stories.mdx, src/components/ui/Checkbox/Checkbox.stories.mdx, src/components/ui/Toast/toast.scss, src/components/ui/Toggle/Toggle.stories.mdx, src/stories/colors.stories.mdx, src/stories/icons.stories.mdx, src/stories/theming.stories.mdx, src/stories/typography.stories.mdx
Improves Storybook titles and section spacing.
=> Fix: Improves Storybook titles

CHANGELOG.md, src/components/ui/Checkbox/Checkbox.tsx, src/components/ui/Checkbox/checkbox.module.scss, src/styles/global/storybook-components.scss, src/styles/pages/plp.scss, src/styles/pages/search.scss
Adapts the `Checkbox` component to use CSS Modules.
The style for the checkbox should be the same as previously.
- [x Added the PR number with the PR link at the entry in the `CHANGELOG.md`. E.g., *New items in the `pull_request_template.md` ([#12](https://github.com/vtex-sites/gatsby.store/pull/12))* 
=> Feat: Uses CSS modules on checkbox component

CHANGELOG.md
This PR updates the CHANGELOG so we can have a new release, following [Base Store Release - May 2022 | FastStore](https://www.faststore.dev/releases/2022/06/03/basestore).
=> Updates CHANGELOG.md with 22.23.0.beta

.storybook/components/BestPractices.tsx, .storybook/components/BestPracticesRule.tsx, .storybook/components/TokenRow.tsx, .storybook/components/index.ts, .storybook/storybook.css, CHANGELOG.md, src/components/ui/Alert/Alert.stories.mdx, src/components/ui/Alert/Alert.tsx, src/components/ui/Button/Button.stories.mdx
Ported from https://github.com/vtex-sites/nextjs.store/pull/101
Following [Fanny's suggestion](https://github.com/vtex-sites/nextjs.store/pull/94#discussion_r889175592), we decided to create a Best Practices section that will first be used at `Alert` doc page.
Also, I updated `Alert` doc page to use `TokenTable`and suggested a new `valueGlobal` prop for when we need to reference a color that's different from `value` prop.
When needed, you can import `BestPractices` and `BestPracticesRule` from `'src/../.storybook/components'` and use it on your `stories.mdx`:
```
<BestPractices>
<BestPracticesRule
recommendedUsage={<RecommendedComponentExample />}
recommendedDescription="..."
discouragedUsage={<DiscouragedComponentExample />}
discouragedDescription="..."
/>
</BestPractices>
```
The result …
=> Feat: Best Practices Section

CHANGELOG.md, package.json, yarn.lock
For more info: https://github.com/vtex/faststore/pull/1399
=> feat: Add priceCurrency to Offer

.storybook/storybook.css, CHANGELOG.md, src/components/cart/CartItem/CartItem.stories.mdx, src/components/product/ProductCard/ProductCard.stories.tsx, src/components/regionalization/RegionalizationModal/RegionalizationModal.stories.mdx, src/components/sections/Hero/Hero.stories.tsx, src/components/ui/Badge/Badge.stories.tsx, src/components/ui/Badge/DiscountBadge.stories.tsx, src/components/ui/Button/Button.stories.mdx, src/components/ui/Dropdown/Dropdown.stories.mdx, src/components/ui/EmptyState/EmptyState.stories.mdx, src/components/ui/InputText/InputText.stories.tsx, src/components/ui/Link/Link.stories.tsx, src/components/ui/PriceRange/PriceRange.stories.mdx, src/components/ui/ProductTitle/ProductTitle.stories.mdx, src/components/ui/QuantitySelector/QuantitySelector.stories.mdx, src/components/ui/Select/Select.stories.tsx, src/components/ui/Toast/Toast.stories.tsx, src/stories/colors.stories.mdx, src/stories/getting-started.stories.mdx, src/stories/global-tokens.stories.mdx, src/stories/icons.stories.mdx, src/stories/theming.stories.mdx, src/styles/global/tokens.scss
> Ported from `next.store` repo: [Storybook Docs Updates #147](https://github.com/vtex-sites/nextjs.store/pull/147)
General updates on the storybook structure and component's pages.
- Updates `Getting started` page
- Adds a Warning Emoji(⚠️) on sidebar titles to WIP components
- Replaces images links (use images hosted on vtex domain)
- Split the component's name on the title to improve readability
- Adjust os `Dropdown` doc page: 
- Replaces `Default` with `Overview`
- Replaces `Related Components` with `Compound Components`
- Updates `Icons` page  ([Add link to current usage mode](https://vtex-dev.atlassian.net/jira/software/projects/FSSS/boards/632/backlog?selectedIssue=FSSS-410))
- Review [Getting Started](https://gatsby-store-storybook-git-chore-storybook-doc-492cf5-faststore.vercel.a …
=> Chore: Storybook Docs Updates

.github/workflows/release.yml
Adds condition to workflow to prevent it from running multiple times for each push.
=> fx: add condition to prevent endless version bumps

src/components/common/Navbar/NavLinks.stories.mdx, src/components/common/Navbar/NavLinks.tsx, src/components/common/Navbar/Navbar.stories.mdx, src/components/common/Navbar/Navbar.tsx, src/components/common/Navbar/navbar.module.scss, src/components/common/Navbar/navlinks.module.scss, src/sdk/ui/useScrollDirection.ts, src/styles/global/tokens.scss
> Ported from `nextjs.store` repo: [Refinements on `Navbar` and `Navlinks` #191](https://github.com/vtex-sites/nextjs.store/pull/191)
This PR follows new styles guidelines for `Navbar` and `Navlinks`
Additionally to visual changes, we added a scroll interaction on desktop:
https://user-images.githubusercontent.com/11613011/182395277-1ff46d43-241d-4ef7-853c-905e7846b114.mov
You can check the [Navbar](https://nextjs-store-storybook-git-feat-refinements-he-78a5d3-faststore.vercel.app/?path=/docs/organisms-navbar-overview--overview-default) and [Navlink](https://nextjs-store-storybook-git-feat-refinements-he-78a5d3-faststore.vercel.app/?path=/docs/organisms-navbar-navlinks--overview-default) stories.  You can also check the scroll effect at the [Demo …
=> feat: Refinements on `Navbar` and `Navlinks`

cypress/integration/analytics.test.js, src/components/sections/ProductShelf/ProductShelf.tsx, src/components/sections/ProductTiles/ProductTiles.tsx, src/components/sections/Section/Section.tsx, src/sdk/search/Sentinel.tsx
See https://github.com/vtex-sites/nextjs.store/pull/242 for the full description and review.
=> fix: `view_item_list` event being fired without products

cypress/integration/analytics.test.js, src/components/cart/CartSidebar/CartSidebar.tsx
A copy from https://github.com/vtex-sites/nextjs.store/pull/247. See the original PR for more details and reviews.
=> feat: Fire `view_cart` event when the minicart is opened

src/components/sections/ProductShelf/ProductShelf.tsx, src/components/sections/ProductTiles/ProductTiles.tsx
A copy from https://github.com/vtex-sites/nextjs.store/pull/251. See the original PR for more details.
=> fix: A regression with CLS on the Home page

package.json, src/api/graphql.ts, src/server/index.ts, yarn.lock
This PR adds `@cacheControl` directive to graphql schema. After this PR, searches and dynamic data will also start being built incrementally, meaning more performance. More info at: https://github.com/vtex/faststore/pull/1473
=> feat: add @cacheControl directive to GraphQL schema

package.json, yarn.lock
This is a fix for this issue: https://github.com/vtex/faststore/pull/1475
=> fix: Wrong sku being returned for slug

src/sdk/ui/useScrollDirection.ts
Taken from https://github.com/vtex-sites/nextjs.store/pull/269
=> chore: use transition api to defer navbar behavior

src/components/sections/BannerText/BannerText.stories.mdx
Ported from https://github.com/vtex-sites/nextjs.store/pull/275
Updates BannerText doc using Tokens components
Everything should look the same on [BannerText stories documentation](https://gatsby-store-storybook-git-chore-update-banner-eb3371-faststore.vercel.app/?path=/docs/organisms-bannertext--banner-text).
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>
<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>
=> doc: Updates documentation using Tokens components
