vtex-sites/gatsby.store

CHANGELOG.md, src/components/regionalization/RegionalizationBar/RegionalizationBar.tsx, src/components/regionalization/RegionalizationButton/RegionalizationButton.tsx
Applies patch from https://github.com/vtex-sites/base.store/pull/495
Update Regionalization Button and Regionalization Bar to show the last postal code saved, instead of receiving a `content` prop.
1- Set a valid postal code in `RegionalizationInput` 
2- Press "enter" key
3- Push the close button.
- [Base store's PR](https://github.com/vtex-sites/base.store/pull/495)
- [Postal Code Bar's original code](https://github.com/vtex-sites/base.store/pull/424)
=> Feat: Update Regionalization Button and Regionalization Bar to show the postal code

CHANGELOG.md, cypress/integration/cart.test.js, src/components/sections/ProductGallery/product-gallery.scss, src/components/ui/EmptyState/EmptyState.tsx, src/components/ui/EmptyState/empty-state.scss, src/styles/pages/homepage.scss, src/styles/pages/layout.scss, src/styles/pages/pdp.scss, src/styles/pages/plp.scss, src/styles/pages/search.scss
Noticed when I visited some pages using their direct URL (not starting from Home and navigating to other pages -- this triggers the loading of missing CSS), the styles for some components were missing. This is due to the split we made in https://github.com/vtex-sites/base.store/pull/480, except we missed some cases.
Before|After
-|-
Compare this vs production versions:
- https://preview-20--gatsby.preview.vtex.app/apple-magic-mouse-99988212/p vs https://gatsby.vtex.app/apple-magic-mouse-99988212/p
- https://preview-20--gatsby.preview.vtex.app/s/?q=mouse&category-2=appliances&facets=category-2&sort=score_desc&page=0 vs https://gatsby.vtex.app/s/?q=mouse&category-2=appliances&facets=category-2&sort=score_desc&page=0
- https://github.com/vtex-sites/base.store/pull/480
=> fix: Fix missing styles

CHANGELOG.md, src/components/ui/Link/Link.stories.tsx, src/components/ui/Link/Link.tsx, src/components/ui/Link/index.ts, src/components/ui/Link/index.tsx, src/components/ui/Link/link.scss
This PR intends to add new tokens to the `Link` component using the [Theming Structure](https://github.com/vtex-sites/base.store/pull/407).
This PR uses local variables to parameterize the `Link` properties, then connects these scoped tokens to the global ones.
None.
| Local token | Default value/Global token linked |
| - | - | 
| `--fs-link-min-width` | `auto` |
| `--fs-link-min-height` | `var(--fs-link-min-width)` |
| `--fs-link-padding` | `var(--fs-spacing-2) var(--fs-spacing-0)` |
| `--fs-link-text-color` | `var(--fs-color-link)` |
| `--fs-link-text-line-height` | `1.5` |
| `--fs-link-text-decoration` | `none` |
| `--fs-link-text-decoration-hover` | `underline` |
| `--fs-link-visited-text-color` | `var(--fs-color-link-visited)` |
| `--fs-link-border-radius` | …
=> feat: Adds new tokens to Link

CHANGELOG.md, src/components/search/Sort/Sort.tsx, src/components/ui/Select/Select.stories.tsx, src/components/ui/Select/Select.tsx, src/components/ui/Select/index.ts, src/components/ui/Select/index.tsx, src/components/ui/Select/select.scss
This PR intends to add new tokens to the `Select` component using the [Theming Structure](https://github.com/vtex-sites/base.store/pull/407).
This PR uses local variables to parameterize the `Select` properties, then connects these scoped tokens to the global ones.
None.
| Local token | Default value/Global token linked |
| - | - | 
| `--fs-select-height` | `var(--fs-spacing-6)` |
| `--fs-select-min-height` | `var(--fs-control-tap-size)` |
| `--fs-select-padding` | `var(--fs-spacing-1) var(--fs-spacing-5) var(--fs-spacing-1) var(--fs-spacing-2)` |
|  |  |
| `--fs-select-text-color` | `var(--fs-color-link)` |
| `--fs-select-border-radius` | `var(--fs-border-radius-default)` |
|  |  |
| `--fs-select-bkg` | `transparent` |
| `--fs-select-bkg-color-focus` | `var(--fs-color-primary-bkg-light)` …
=> feat: Adds new tokens to Select

CHANGELOG.md, package.json, src/Layout.tsx, src/components/sections/ProductShelf/ProductShelf.tsx, src/components/sections/ProductTiles/ProductTiles.tsx, src/pages/[...slug].tsx, src/pages/[slug]/p.tsx, src/pages/index.tsx, src/sdk/person/usePersonQuery.ts, yarn.lock
One of the main problems of the home page that impacts the performance is the total blocking time (TBT).
This PR tries to decrease the TBT and improve the performance score overall on the home page.
The highest task is the react first render. So investigating the components that have the most impact on this huge task, I discovered that the first component that uses the hook `useSWR` suffers from the compilation code from SWR and we can't avoid, but can delay. This component is the ButtonSignIn, that has usePersonQuery, that uses the useQuery.
As you can see, the self time is ~0, the rest comes from useSWR.
Also, this PR suspends the ProductShelf and ProductTiles queries, so these components are removed from the first render, because of the task that contains the first render decrease the …
=> chore: home performance improvements

CHANGELOG.md, src/components/ui/Badge/Badge.stories.tsx, src/components/ui/Badge/Badge.tsx, src/components/ui/Badge/badge.scss
This PR renames the `Badge` prop according to the listed on Figma and follows `InputText` pattern https://github.com/vtex-sites/gatsby.store/pull/15.
`interactive` -> `actionable`
Ps: Also renamed `children` to `content` on the stories to be more explicit about that control purpose. 
|Before|After|
|-|-|
`interactive` prop became `actionable`
Nothing should change visually on the component, and everything should work fine.
=> chore: Rename Badge prop 

CHANGELOG.md, src/components/sections/ProductGallery/ProductGallery.tsx, src/components/sections/ProductGallery/useDelayedPagination.ts
This PR fixes a hydration mismatch at https://gatsby.vtex.app/office?page=1
By visiting the aforementioned page we receive a hydration mismatch error. To address this problem, we need to lazy render prev/next links. 
Open the preview at `/office?page=1` and make sure no error is thrown. Also, make sure other urls work fine.
=> fix: Hydration mismatch

CHANGELOG.md, src/components/ui/Image/Image.tsx, src/components/ui/ImageGallery/ImageGallerySelector.tsx, src/components/ui/ImageGallery/image-gallery-selector.scss
This PR fixes the behavior of the ImageGallery, implementing toggle rules for the arrows that are used to navigate in the image minatures:
- The right/up arrow only shows when the first image is not visible
- The left/down arrow only shows when the last image is not visible
It uses the `inView` value for the first and last images, added using the `useInView()` hook. 
- If the `inView` for the first image is `true`, then the left (mobile)/up (desktop) arrow is not displayed. It is displayed when `inView` is `false`.
- _This means that the arrow is hidden when we are at the beginning of the image miniatures list, and displayed when we start navigating towards the end of the images._
- If the `inView` for the last image is `true`, then the right (mobile)/down (desktop) arrow is not …
=> fix: Toggle arrows at the ImageGallery in accordance to scroll position

CHANGELOG.md, src/pages/[...slug].tsx, src/pages/[slug]/p.tsx, vtex.env
This PR uses the new WebOps capability called Incremental Static Builds. This should drastically improve response times and reduce infrastructure usage on deferred pages, like PDPs and PLPs
WebOps recently released this Incremental Static Builds feature. To use on Gatsby, make sure to return the following cache-control headers on SSR pages:
```
'cache-control': 's-maxage=31536000, stale-while-revalidate',
```
and enable `USE_STALE_CACHE=true` on `vtex.env`.
Open a PDP. Check the response header called `x-faststore-cache`. The first request should give you a `MISS`. The second request should give you `HIT`. Note that `HIT`s are much faster than `MISS`. Also, note that all subsequent requests have a HIT as value. 
- Original PR on WebOps: https://github.com/vtex/vtex-cicd-platform/pull/105
=> feat: Incremental Static Build

.storybook/main.js, CHANGELOG.md
Previously we removed `@reach/router` from our [package.json](https://github.com/vtex-sites/gatsby.store/pull/42/files) because we are using `@gatsbyjs/reach-router` instead. But we're still using it on the storybook, and it is currently broken. To avoid it, I've added an alias.
Ps: Let's see later if we can handle this situation with another approach.  
It should fix storybook build.
The storybook [preview](https://gatsby-store-storybook-git-fix-storybook-router-alias-faststore.vercel.app/?path=/story/releases-changelog--page) should be working fine.
[@gatsbyjs/reach-router](https://www.npmjs.com/package/@gatsbyjs/reach-router)
[webpack.js.org](https://webpack.js.org/configuration/resolve/#resolvealias)
=> fix: Resolves `@reach/router` on storybook

CHANGELOG.md, src/components/sections/Hero/Hero.tsx, src/components/ui/Image/Image.tsx, src/components/ui/ImageGallery/ImageGallery.tsx
This PR intends to fix global props being visible/possible for types/interfaces extended from a global interface.
In the `Image` component we declared some props for the React global interface, `HTMLAttributes`, and it affected other components. We could detect this by looking into Storybook args for any component:
With these changes, we narrowed the custom attributes only to the specific HTML tags `img` and `link`.
It can be tested by looking into the components' Storybook args and checking if any of the custom attributes (i.e, `fetchPriority`) are visible.
=> fix: Fixes custom attributes for `img` and `link` tags

src/components/ui/Image/Image.tsx
This PR intends to fix a `link` attribute typo. (`imageSizes` instead `imagesizes`). For the Gatsby local build, we can't see the log warning.
Just try to build locally and go to the homepage, the terminal should not show the warning again.
=> fix: Fixes <link /> attribute typo

CHANGELOG.md, src/components/ui/QuantitySelector/QuantitySelector.tsx, src/components/ui/QuantitySelector/quantity-selector.module.scss, src/styles/global/storybook-components.scss, src/styles/pages/pdp.scss
This PR uses CSS modules to import the QuantitySelector component.
<em>Tell us the role of the new feature, or component, in its context.</em>
Check if the `QuantitySelector` works at the cart and at the PDP.
=> chore: Uses CSS Modules on `QuantitySelector`

src/components/ui/QuantitySelector/quantity-selector.module.scss
Little reactoring to move the variant `data-attribute` of the `QuantitySelector` inside the main class.
QuantitySelector should work at cart and PDP
I've skiped the Changelog for this one.
=> fix: Moves `QuantitySelector` variant attribute inside css class

pull_request_template.md
Fixed the names of the responsible for doc review in the `pull_request_template.md` file.
=> Doc: fixed doc responsible names

CHANGELOG.md, src/components/ui/Toggle/Toggle.stories.mdx
This PR removes some unused `-default` variables that are being used on our code. This nomenclature was removed at #28 but after [this PR](https://github.com/vtex-sites/nextjs.store/pull/61#discussion_r885095969) in `nextjs.store`. I've checked and fount out it's being used in some places, yet.
This PR just removes the `-default` nomenclature from variables where it's possible.
Look around the preview and storybook. It should be working with the variables.
- https://github.com/vtex-sites/nextjs.store/pull/61#discussion_r885095969)
=> fix: Removes unused `-default` at css variables

.storybook/components/TokenDivider.tsx, .storybook/components/TokenRow.tsx, .storybook/components/TokenTable.tsx, .storybook/components/index.ts, CHANGELOG.md, src/components/ui/QuantitySelector/QuantitySelector.stories.mdx, src/components/ui/QuantitySelector/QuantitySelector.tsx
Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
This PR adds storybook documentation for QuantitySelector component.
Added the TokenTable and TokenRow components to make it easier to document tokens in the storybook.
Run storybook and see `http://localhost:6006/?path=/docs/organisms-quantityselector--quantity-selector`.
=> feat: Add document in `QuantitySelector`

src/pages/[...slug].tsx, src/pages/[slug]/p.tsx
Fix wrong 404 during SSG
When an error occurs while fetching data needed for pages during SSG, our code threats this as a notFound. This notFound is SSG and this page will be notFound until we make a new deploy. This PR fixes this issue by throwing and error if an error occurs, making this page to be re-generated on the next request, thus generating the right page.
1. Run `yarn build && yarn serve` on your machine
2. Remove internet access (disable wifi) from your machine to simulate a communication error between the server and VTEX commerce platform
3. Enter in a PDP. You should see the 500 error page.
4. Re-enable the wifi and refresh. You should now see the correct page.
=> fix: Static incremental builds errors

CHANGELOG.md, src/components/sections/ProductShelf/ProductShelf.tsx, src/components/sections/ProductTiles/ProductTiles.tsx, src/pages/index.tsx, src/sdk/product/useProductsQuery.ts
This PR simplifies a bit how we handled Suspense in our components. 
Before this PR, we had [this if logic](https://github.com/vtex-sites/gatsby.store/blob/e041beb86df3f57292b497eae0ef47d91672a3af/src/components/sections/ProductShelf/ProductShelf.tsx#L27) for suspense and this [unnecessary fallback value](https://github.com/vtex-sites/gatsby.store/blob/e041beb86df3f57292b497eae0ef47d91672a3af/src/components/sections/ProductShelf/ProductShelf.tsx#L14) data on the `swr` hook. This PR removes those and makes suspense the default behavior. You can disable suspense if you wish
- Nothing should have changed from master
=> feat: React 18 features

CHANGELOG.md, src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
Fix Region Input's behavior when setting zipCode
When using `Mutation.validateSession` query, `RegionalizationInput` component was passing an extra variable that was not defined on the GraphQL schema, breaking the query with the following error:
This PR addresses this issue by removing the `isValidating` variable from session.
Open the deploy preview, set the zip code and make sure the zip code is set on the UI without errors on console like so:
=> fix: Region Input

.storybook/preview.js, CHANGELOG.md, package.json, src/components/search/Suggestions/SuggestionsTopSearch.stories.tsx, static/mockServiceWorker.js, yarn.lock
Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
This PR adds the [Mock Service Worker Addon](https://storybook.js.org/addons/msw-storybook-addon) in storybook, and configures the API mock for TopSearch component. 
The result can be seen in [TopSearch storybook preview](https://nextjs-store-storybook-git-add-storybook-msw-addon-faststore.vercel.app/?path=/docs/features-search-topsearch--default)
[Mock Service Worker Addon](https://storybook.js.org/addons/msw-storybook-addon)
**Changelog**
=> feat: Add MSW addon config

CHANGELOG.md, src/Layout.tsx, src/components/ui/Modal/Modal.tsx, src/sdk/tests/index.tsx, src/sdk/ui/Provider.tsx
ported from https://github.com/vtex-sites/nextjs.store/pull/127
But also fixes:
**Changelog**
=> fix: SonarQube warnings/error

CHANGELOG.md, src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx, src/components/ui/InputText/InputText.stories.tsx, src/components/ui/InputText/InputText.tsx
This PR intends to fix the `InputText` by removing some component's local implementation, which should be the responsibility of the parent component that is rendering it.
Previously, some main attributes were being defined inside `InputText` component (e.g. `onInput` and `value`) and by doing this, parent components rendering the `InputText` had limitations using the same attributes.
The component should look the same as before. The main difference is the change of the responsibility to implement input's required attributes to the parent.
**Changelog**
=> fix: Transfers responsibility of `InputText`'s main attributes and callbacks to the renderer

CHANGELOG.md, package.json, yarn.lock
From 6.6.0. This way, it matches [Cypress version run by WebOps that was recently updated][1].
[1]: https://github.com/vtex/vtex-cicd-platform/pull/182
Run `yarn develop` and then `yarn test`.
=> chore: Improve integration tests by upgrading Cypress to 9.6.5

CHANGELOG.md, package.json, yarn.lock
From 9.5.4. This way, it matches [Cypress version run by WebOps that was recently updated][1].
[1]: https://github.com/vtex/vtex-cicd-platform/pull/217
Run `yarn develop` and then `yarn test`.
Similar to https://github.com/vtex-sites/gatsby.store/pull/148.
=> chore: Improve integration tests by upgrading Cypress to 9.6.0

.prettierignore, static/mockServiceWorker.js
The release bot is failing because the msw file that's auto-generated is not formatted when you clone the repo and install dependencies. This is not ideal, since this means the version of the code that is versioned is (slightly) different from that which is actually shipped.
Ignoring this auto-generated file from prettier rules fixes the issue.
=> fix: prettier ignore auto-generated file

pull_request_template.md
This PR updates the PR template to reflect recent changes in the changelog.
I've added checklists regarding PR titles and commit messages and removed old ones regarding changelog entries
=> chore: Update PR template to reflect recent changelog changes 

src/components/ui/InputText/input-text.scss, src/components/ui/PriceRange/PriceRange.stories.mdx, src/components/ui/PriceRange/PriceRange.tsx, src/components/ui/PriceRange/price-range.module.scss, src/sdk/product/useFormattedPrice.ts, src/styles/global/tokens.scss
> Ported from `next.store` repo: [Feat: adds tokens to PriceRange #146](https://github.com/vtex-sites/nextjs.store/pull/146)
This PR applies the new [Theming structure](https://github.com/vtex-sites/base.store/pull/407) to `PriceRange`: new scoped tokens linked to global ones.
This PR uses local variables to parameterize the `PriceRange` properties, then connects these scoped tokens to the global ones.
Tokens list can be visualized in the [Storybook](https://gatsby-store-storybook-git-feat-theming-price-4e6ef5-faststore.vercel.app/?path=/docs/molecules-pricerange--overview-default).
- The `PriceRange` component and its related components should look just as it was before these changes.
- You can check the [story on Storybook](https://gatsby-store-storybook-git-feat-theming-price-4e6ef5-fas …
=> Feat: adds tokens to `PriceRange`

src/components/sections/BannerText/BannerText.stories.mdx, src/pages/index.tsx
Ported from https://github.com/vtex-sites/nextjs.store/pull/198
Just improving the BannerText content example to avoid misleading.
Replaced Receive our news and promotions in advance. Enjoy and get 10% off on your first purchase.
with The sun has set on our Summer Sale! Save up to 50% off. Don't miss out!
Everything should work fine. Only changed the text example.
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>
<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>
=> chore: Updates `BannerText` content example

src/components/common/Navbar/Navbar.tsx, src/components/search/SearchInput/SearchInput.tsx, src/components/search/SearchInput/index.tsx
> Ported from `nextjs.store` repo: [Avoids performing the search when user abandons the query #193](https://github.com/vtex-sites/nextjs.store/pull/193)
This PR intends to fix the behavior when users abandon the search query and then click on the search icon again, automatically performing the search with the previous query.
Note that this behavior only happens and will be fixed in the mobile version. For the desktop version, the `SearchInput` bar persists what the user typed but without doing the automatic search.
With these changes, an imperative handle was created for the `SearchInput` ref used in the `Navbar` component, so when users cancel the search action this handler is triggered and clears the input.
Steps to reproduce (mobile version):
- Expand the search input and type …
=> fix: Avoids performing the search when user abandons the query

.storybook/storybook.css, src/components/common/Navbar/navlinks.module.scss
Ported from https://github.com/vtex-sites/nextjs.store/pull/212
- Attempts to fix `SearchDropdown` displaying below navlinks
- Follow-up https://github.com/vtex-sites/nextjs.store/pull/191#pullrequestreview-1061668003
Changes back `z-index: var(--fs-z-index-below)`
|Current|Fixed|
|-|-|
|<img width="1154" alt="image" src="https://user-images.githubusercontent.com/3356699/185451624-b40bd241-147b-484e-a5fe-dae9ad8d2ce6.png">|<img width="1423" alt="image" src="https://user-images.githubusercontent.com/3356699/185452126-531a5962-849d-4434-bbeb-8a31e241545b.png">|
- Check on the [preview](https://preview-212--nextjs.preview.vtex.app) if the search dropdown is being displayed correctly.
- Also verify if [navlinks](https://nextjs-store-storybook-git-fix-navlink-z-index-faststore.vercel.app/?path= …
=> fix: Display `SearchDropdown` correctly

cms/sections.json
Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
This PR fix the config from storeframework CMS to be possible adds the IncentivesHeader and BannerText variant.
Fix sections.json config.
View the [preview](https://sfj-7f9092f--gatsby.preview.vtex.app/) and use the [Storeframework CMS.]( https://storeframework.myvtex.com/admin/new-cms/faststore/home/edit/ad2fd81d-a53c-4281-8d01-a4fc2f274db3/)
https://www.faststore.dev/tutorials/cms/3
=> fix: Fix cms config

.storybook/storybook.css, src/components/ui/Button/Button.stories.mdx, src/components/ui/Button/button.module.scss
> Ported from `nextjs.store` repo: [Include Button with only an icon on Storybook #213](https://github.com/vtex-sites/nextjs.store/pull/213)
This PR intends to include the old `ButtonIcon` case as a related component on Storybook.
It can be seen on `Button` story, in the _Related Components_ section (Storybook)
=> chore: Include `Button` with only an icon on Storybook

src/components/common/Navbar/navlinks.module.scss
A direct copy from https://github.com/vtex-sites/nextjs.store/pull/224. Please see the original PR for more details.
=> fix: Navigation links on mobile not being clickable

package.json, src/components/cart/CartItem/CartItem.tsx, yarn.lock
Please see https://github.com/vtex-sites/nextjs.store/pull/239.
=> refactor: Extract `CartItem` from the starter to `@faststore/ui`

src/components/ui/SkuSelector/SkuSelector.tsx, src/components/ui/SkuSelector/index.ts
Extract the `SkuSelector` component to the `@faststore/ui` package. The component has been moved.
Check that the component is still functional in the following previews:
- https://sfj-be687b0--gatsby.preview.vtex.app/apple-magic-mouse-99988212/p
- https://gatsby-store-storybook-ign8iepie-faststore.vercel.app/?path=/docs/molecules-skuselector-overview--overview-default-1
https://github.com/vtex/faststore/pull/1462
=> refactor: Extract `SkuSelector` component to `@faststore/ui`

src/components/regionalization/Regionalization.stories.mdx, src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx, src/components/regionalization/RegionalizationModal/RegionalizationModalContent.tsx, src/components/sections/ProductDetails/ProductDetails.tsx, src/components/sections/ProductDetails/product-details.scss, src/components/ui/ImageGallery/image-gallery.module.scss, src/components/ui/InputText/InputText.tsx, src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx, src/components/ui/ShippingSimulation/ShippingSimulation.tsx, src/components/ui/ShippingSimulation/index.tsx, src/components/ui/ShippingSimulation/shipping-simulation.module.scss, src/components/ui/ShippingSimulation/useShippingSimulation.ts
> Ported from `nextjs.store` repo: [Feat: [Refinements] Creates ShippingSimulation #183](https://github.com/vtex-sites/nextjs.store/pull/183)
This PR aims to create and refine the `ShippingSimulation` that is found in the PDP.
**This task didn't include API integration**. Thus, we are using mocked data just to see the component working as expected.
---
Tasks:
|Desktop|Mobile|
|-|-|
|![06VzGVSK2e](https://user-images.githubusercontent.com/11325562/181630177-b552834f-ed82-46e4-a2ff-f15ccdb2bd93.gif)|![mobile-shipping-simulation](https://user-images.githubusercontent.com/11325562/181629024-90b4ef96-48b8-43fc-8355-2bbeae2cec3a.gif)|
👀  One behavior to pay attention to: 
- if the user had a `PostalCode` included in its session, the page should load this `PostalCode` in the `ShippingSimulation` …
=> Feat: [Refinements] Creates `ShippingSimulation`

src/components/cart/CartToggle/CartToggle.tsx, src/components/cart/CartToggle/cart-toggle.scss, src/components/common/Navbar/navbar.module.scss
ported from https://github.com/vtex-sites/nextjs.store/pull/276
Update CartToggle data-attr from data-fs-button-cart to data-fs-cart-toggle
Everything should look the same.
=> chore: Renames data-attr

src/sdk/analytics/index.tsx, src/sdk/analytics/platform/vtex/search.ts
This PR aims to address some `ChunkLoadError` from the analytics Provider that we got from some clients (sentry).
It looks like this dynamic import is bringing some `ChunkLoadError`. So we transformed it into a static import and added a guard clause to prevent Reference errors using the navigator object on the Server Side.
* We dynamically import for the sake of initial JS loading. Then we need to pay attention if LH scores keep high after these changes.
The `ChunkLoadError` from the analytics module in sentry should decrease. Everything in the store should look the same. 
https://github.com/gatsbyjs/gatsby/issues/18866
https://github.com/gatsbyjs/gatsby/pull/33032
https://github.com/gatsbyjs/gatsby/pull/34225/files
=> Fix: chunk load analytics
